config/routes.rb
Rails.application.routes.draw do

  get 'pages/user'

  get '/home' => 'pages#home'

  get '/dashboard' => 'pages#dashboard'

  get '/blog'=> 'pages#blog'
  
  controller :sessions do
	  
	  get 'login'=> :new
	  
	  post 'login'=> :create
	  
	  get 'logout'=> :destroy

	  delete 'logout'=> :destroy
	end
	
   resources :posts do
	resources :comments
   end

  
  

  resources :dashboards
  resources :comments
  resources :posts
  resources :blogs
  resources :users
  

   root 'pages#home'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base

	belongs_to :user
	belongs_to :blog
	
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_filter :authorise
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show_dash
  @user = User.find(params[:id])
  @posts = @user.posts
end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit(:dash_name, :blog_id, :user_id)
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<center><%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dash_name %><br>
    <%= f.text_field :dash_name %>
  </div>
  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.collection_select :blog_id, Blog.all, :id, :blog_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<center><p id="notice"><%= notice %></p>

<h1>Listing Dashboards</h1>

<table>
  <thead>
    <tr>
      <th>Dash name</th>
      <th>Blog</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= dashboard.dash_name %></td>
        <td><%= dashboard.blog_id %></td>
        <td><%= dashboard.user_id %></td>
        <td><%= link_to 'Show', dashboard %></td>
		<td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dashboard', new_dashboard_path %>
</center>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dash name:</strong>
  <%= @dashboard.dash_name %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @dashboard.blog_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @dashboard.user_id %>
</p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>